apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secure-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secure-app.labels" . | nindent 4 }}
data:
  APP_ENV: "production"
  APP_PORT: "{{ .Values.service.targetPort }}"
